### ISSUE TITLE
Columns of Blog page on Notion

### ISSUE THREAD

**Issue by hthoai** [ArnaudValensi/ArnaudValensi.github.io#2]
Hi, could you please show me the name of all the columns on the Blog page? I have `title`, `date`, `description`, and `slug` but it occurred bug when deploying.
![Capture1](https://user-images.githubusercontent.com/28279782/95469074-67c4b600-09a9-11eb-9c30-1729a2bbe4ac.PNG)
![Capture2](https://user-images.githubusercontent.com/28279782/95469090-6abfa680-09a9-11eb-8935-c0b483331146.PNG)

**Comment by ArnaudValensi** [comment]
Hi,

The import script will convert any text line starting by `==` to a markdown frontmatter metadata, but it doesn't use page properties like you are trying to do.

Let's say you have this in your Notion note:

```
== date: 2020-09-17
== description: How to use notion as a content manager to generate a static blog.
```

In markdown it will become:

```
---
date: 2020-09-17
description: How to use Notion as a content manager to generate a static blog.
---
```

Also, the cover image of your notion page will be downloaded and converted to:

```
---
...
featured: '0ca01e654f193b6555f25ba69613ee1ad67d8e71.jpeg'
---
```

More info [here](https://arnaudvalensi.github.io/blog/making-a-blog-using-notion-gatsby-and-github-pages/)

**Comment by hthoai** [comment]
So I need to add those metadata first?!

**Comment by ArnaudValensi** [comment]
Yes, `date` and`description`. Also you have to add a cover picture.
See this https://github.com/ArnaudValensi/ArnaudValensi.github.io/issues/1

**Comment by hthoai** [comment]
I have error with the cover image :<
`Successfully created virtual environment!
Virtualenv location: /home/runner/.local/share/virtualenvs/hthoai.github.io-afcMCu_n
Installing dependencies from Pipfile.lock (e734c5)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
-> Cleaning the "content/blog" folder
-> Downloading https://s3-us-west-2.amazonaws.com/secure.notion-static.com/ab93fa8f-3480-4847-b629-32e6649bcbdf/cfc69dd09e2c11e8b99ab9374b211b7c.jpg
Traceback (most recent call last):
  File "./bin/get-blog-posts.py", line 146, in <module>
    to_markdown(root_page_id, ignore=ignore_root)
  File "./bin/get-blog-posts.py", line 125, in to_markdown
    text, child_metas = process_block(page)
  File "./bin/get-blog-posts.py", line 95, in process_block
    subpage_slug = to_markdown(content.id, ignore=False)
  File "./bin/get-blog-posts.py", line 125, in to_markdown
    text, child_metas = process_block(page)
  File "./bin/get-blog-posts.py", line 77, in process_block
    image_name = download_file(content.source, dest_path)
  File "./bin/get-blog-posts.py", line 32, in download_file
    r = requests.get(file_url, stream=True)
  File "/home/runner/.local/share/virtualenvs/hthoai.github.io-afcMCu_n/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/runner/.local/share/virtualenvs/hthoai.github.io-afcMCu_n/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/runner/.local/share/virtualenvs/hthoai.github.io-afcMCu_n/lib/python3.8/site-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/home/runner/.local/share/virtualenvs/hthoai.github.io-afcMCu_n/lib/python3.8/site-packages/requests/sessions.py", line 449, in prepare_request
    p.prepare(
  File "/home/runner/.local/share/virtualenvs/hthoai.github.io-afcMCu_n/lib/python3.8/site-packages/requests/models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "/home/runner/.local/share/virtualenvs/hthoai.github.io-afcMCu_n/lib/python3.8/site-packages/requests/models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
Error: Process completed with exit code 1.
`

**Comment by ArnaudValensi** [comment]
This problem is answered here https://github.com/ArnaudValensi/ArnaudValensi.github.io/issues/1#issuecomment-704831134

**Comment by hthoai** [comment]
I deployed successfully. Is there something wrong? I can't reach my site:
![Capture](https://user-images.githubusercontent.com/28279782/95537142-20750e80-0a17-11eb-87ea-6227eecf98a0.PNG)

**Comment by ArnaudValensi** [comment]
I suggest you to read the documentation of github pages https://pages.github.com/

Have you tryed to host a simple `index.html` with anything in it the see if your github page is well configured ?

**Comment by hthoai** [comment]
Yep, I used to. I think Github Action will generate it :- So I need to do it manually?

My repo for Github Pages has the similar structure with yours
![Capture](https://user-images.githubusercontent.com/28279782/95587939-ef272d80-0a6c-11eb-9ad6-5dde07ae408a.PNG)

**Comment by ArnaudValensi** [comment]
Ok and do you have a `gh-page` branch?

<img width="1019" alt="Capture d’écran 2020-10-09 à 15 30 18" src="https://user-images.githubusercontent.com/604486/95589161-aa879c00-0a44-11eb-80a3-831a8aa01194.png">

And in the settings, is github page setup to use the `gh-page` branch?

<img width="1138" alt="Capture d’écran 2020-10-09 à 15 31 06" src="https://user-images.githubusercontent.com/604486/95589244-c25f2000-0a44-11eb-8468-7378e1c9edef.png">
<img width="833" alt="Capture d’écran 2020-10-09 à 15 31 40" src="https://user-images.githubusercontent.com/604486/95589254-c723d400-0a44-11eb-9dd4-4859eb11e0d3.png">

**Comment by hthoai** [comment]
I dit it! Thank you for your enthusiastic support. I'm in love with and now with your repo. It's exactly what I need <3
