### ISSUE TITLE
update notion authorized  

### ISSUE THREAD

**Issue by eveningcafe** [ArnaudValensi/ArnaudValensi.github.io#28]
Please update readme , the author method was change
https://developers.notion.com/docs/getting-started

Otherwise we'll get err ( status":401,"code":"unauthorized" )

**Comment by tkasarla** [comment]
@eveningcafe I get the same error, how do I make sure the pages are read? I have already changed the auth method and key.

**Comment by eveningcafe** [comment]
my solution is learn markdown. notion note just for save ideal and stub.

**Comment by eveningcafe** [comment]
you can try hugo

**Comment by tkasarla** [comment]
@ArnaudValensi @eveningcafe Ah, thanks, I do know markdown and use it for my personal webpage. but this is something for a webpage that everyone in my group can maintain on Notion and read and uploaded to github through this repo. If you do know some other workaround for the authentication, let me know. I will also check Hugo to see if it fits my needs.
